import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const grostek = localFont({
  src: './fonts/Grostek-vf.ttf',
  variable: "--font-grostek",
  display: "swap",
  preload: true,
});

const grostekItalic = localFont({
  src: './fonts/Grostek-italic-vf.ttf',
  variable: "--font-italic-grostek",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${grostek.variable} ${grostekItalic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
